version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: employee
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 30s

  backend:
    image: akta2910/employee-backend:latest 
    container_name: springboot-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/employee?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "9090:9090"
    networks:
      - app-network
    restart: on-failure

  frontend:
    image: akta2910/employee-frontend:latest 
    container_name: react-app
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:

volumes:
  mysql_data:
